package com.briup.apps.cms.bean;

public class Userrole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_role.id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_role.user_id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_role.role_id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_role.id
     *
     * @return the value of cms_user_role.id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_role.id
     *
     * @param id the value for cms_user_role.id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_role.user_id
     *
     * @return the value of cms_user_role.user_id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_role.user_id
     *
     * @param userId the value for cms_user_role.user_id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_role.role_id
     *
     * @return the value of cms_user_role.role_id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_role.role_id
     *
     * @param roleId the value for cms_user_role.role_id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}