package com.briup.apps.cms.bean;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.username
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.password
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.telephone
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.realname
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.gender
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.brith
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private Date brith;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.register_time
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.status
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.user_face
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    private String userFace;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.id
     *
     * @return the value of cms_user.id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.id
     *
     * @param id the value for cms_user.id
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.username
     *
     * @return the value of cms_user.username
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.username
     *
     * @param username the value for cms_user.username
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.password
     *
     * @return the value of cms_user.password
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.password
     *
     * @param password the value for cms_user.password
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.telephone
     *
     * @return the value of cms_user.telephone
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.telephone
     *
     * @param telephone the value for cms_user.telephone
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.realname
     *
     * @return the value of cms_user.realname
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.realname
     *
     * @param realname the value for cms_user.realname
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.gender
     *
     * @return the value of cms_user.gender
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.gender
     *
     * @param gender the value for cms_user.gender
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.brith
     *
     * @return the value of cms_user.brith
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public Date getBrith() {
        return brith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.brith
     *
     * @param brith the value for cms_user.brith
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setBrith(Date brith) {
        this.brith = brith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.register_time
     *
     * @return the value of cms_user.register_time
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.register_time
     *
     * @param registerTime the value for cms_user.register_time
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.status
     *
     * @return the value of cms_user.status
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.status
     *
     * @param status the value for cms_user.status
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.user_face
     *
     * @return the value of cms_user.user_face
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public String getUserFace() {
        return userFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.user_face
     *
     * @param userFace the value for cms_user.user_face
     *
     * @mbg.generated Wed Nov 13 09:29:28 CST 2019
     */
    public void setUserFace(String userFace) {
        this.userFace = userFace == null ? null : userFace.trim();
    }
}