package com.syu.apps.cms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.syu.apps.cms.bean.Mytest;
import com.syu.apps.cms.bean.MytestExample;

public interface MytestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    long countByExample(MytestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    int deleteByExample(MytestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    int insert(Mytest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    int insertSelective(Mytest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    List<Mytest> selectByExampleWithBLOBs(MytestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    List<Mytest> selectByExample(MytestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    Mytest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Mytest record, @Param("example") MytestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Mytest record, @Param("example") MytestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    int updateByExample(@Param("record") Mytest record, @Param("example") MytestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    int updateByPrimaryKeySelective(Mytest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_mytest
     *
     * @mbg.generated Tue Nov 12 10:57:48 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Mytest record);
}