package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.Userrole;
import com.briup.apps.cms.bean.UserroleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 10:05:29 CST 2019
     */
    long countByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 10:05:29 CST 2019
     */
    int deleteByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 10:05:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 10:05:29 CST 2019
     */
    int insert(Userrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 10:05:29 CST 2019
     */
    int insertSelective(Userrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 10:05:29 CST 2019
     */
    List<Userrole> selectByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 10:05:29 CST 2019
     */
    Userrole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 10:05:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") Userrole record, @Param("example") UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 10:05:29 CST 2019
     */
    int updateByExample(@Param("record") Userrole record, @Param("example") UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 10:05:29 CST 2019
     */
    int updateByPrimaryKeySelective(Userrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 10:05:29 CST 2019
     */
    int updateByPrimaryKey(Userrole record);
}